/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LivetvRouteImport } from './routes/livetv'
import { Route as CustomizeRouteImport } from './routes/customize'
import { Route as AnimeRouteImport } from './routes/anime'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as AnimeIdRouteImport } from './routes/anime.$id'

const LivetvRoute = LivetvRouteImport.update({
  id: '/livetv',
  path: '/livetv',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeRoute = CustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeRoute = AnimeRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIdRoute = AnimeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AnimeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anime': typeof AnimeRouteWithChildren
  '/customize': typeof CustomizeRoute
  '/livetv': typeof LivetvRoute
  '/anime/$id': typeof AnimeIdRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anime': typeof AnimeRouteWithChildren
  '/customize': typeof CustomizeRoute
  '/livetv': typeof LivetvRoute
  '/anime/$id': typeof AnimeIdRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anime': typeof AnimeRouteWithChildren
  '/customize': typeof CustomizeRoute
  '/livetv': typeof LivetvRoute
  '/anime/$id': typeof AnimeIdRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anime'
    | '/customize'
    | '/livetv'
    | '/anime/$id'
    | '/watch/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anime' | '/customize' | '/livetv' | '/anime/$id' | '/watch/$id'
  id:
    | '__root__'
    | '/'
    | '/anime'
    | '/customize'
    | '/livetv'
    | '/anime/$id'
    | '/watch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimeRoute: typeof AnimeRouteWithChildren
  CustomizeRoute: typeof CustomizeRoute
  LivetvRoute: typeof LivetvRoute
  WatchIdRoute: typeof WatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/livetv': {
      id: '/livetv'
      path: '/livetv'
      fullPath: '/livetv'
      preLoaderRoute: typeof LivetvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize': {
      id: '/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof CustomizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime': {
      id: '/anime'
      path: '/anime'
      fullPath: '/anime'
      preLoaderRoute: typeof AnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$id': {
      id: '/anime/$id'
      path: '/$id'
      fullPath: '/anime/$id'
      preLoaderRoute: typeof AnimeIdRouteImport
      parentRoute: typeof AnimeRoute
    }
  }
}

interface AnimeRouteChildren {
  AnimeIdRoute: typeof AnimeIdRoute
}

const AnimeRouteChildren: AnimeRouteChildren = {
  AnimeIdRoute: AnimeIdRoute,
}

const AnimeRouteWithChildren = AnimeRoute._addFileChildren(AnimeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimeRoute: AnimeRouteWithChildren,
  CustomizeRoute: CustomizeRoute,
  LivetvRoute: LivetvRoute,
  WatchIdRoute: WatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
